@startumlpackage mdi{class Menu{  - menu : Menu  - view : List..  + {static} main(args: String[])  + toString() : String <<override>>..  - quit()  - rockPaperScicsors()  - chicken()  - princessMonster()}}package princessMonster{}package chicken{class Board{  - player : Tractor  - ai : Tractor  + movePlayer()  + detectCollisions()  + playerIsAlive()}class Tractor{  - isAlive : boolean  + move()  + isAlive() : boolean  }}package rockPaperScicsors{class Board{  - player : Player  - robot : Player    }class Player{}}package Game{class Game{  - board : board  - {static} clearScreen : String  + Game()  + executeCommand(cmd : char) : boolean  + printBanner()  + printHelp()  + printTrophy()}}Menu *- chickenMenu *- rockPaperScicsors@enduml